name: dart_ci
version: 0.3.0

publish_to: none
environment:
  sdk: ^3.11.0

dependencies:
  _discoveryapis_commons: ^1.0.2
  args: ^2.3.1
  googleapis: ^16.0.0
  googleapis_auth: ^2.1.0
  http: ^1.6.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
