name: dart_ci
version: 0.2.0

publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  _discoveryapis_commons: ^0.1.3+1
  args: ^1.5.0
  googleapis: ^0.51.0
  googleapis_auth: ^0.2.7
  http: ^0.11.1+1
