name: builder
description: Scripts run on Dart CQ/CI builders
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.1 # The recipe will use this exact version.

dependencies:
  args: ^2.3.0
  googleapis_auth: ^2.0.0
  googleapis: ^15.0.0
  http: ^1.1.0
  pool: ^1.5.0
  retry: ^3.1.0
  collection: ^1.15.0
  glob: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.9.4
