name: baseline
description: Baselines a Dart CI builder.
publish_to: none
version: 0.0.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  args: ^2.3.0
  pool: ^1.5.0

dev_dependencies:
  io: ^1.0.3
  lints: ^6.1.0
  test: ^1.17.12
